version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_PWD=oracle123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/oracle123@//localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./Tienda-FullStack
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521:XE
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      oracle:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  oracle-data: